services:
  openldap:
    build:
      context: ..
      args:
        ALPINE_VERSION: ${ALPINE_VERSION:-3.24}
        OPENLDAP_CHANNEL: ${OPENLDAP_CHANNEL:-lts}
        OPENLDAP_VERSION: ${OPENLDAP_VERSION:-2.6.14}
        OPENLDAP_SHA256: ${OPENLDAP_SHA256:-806dcd21d366428187fba3278da773d5930f774852c9e92517f950d585f19107}
    image: ${IMAGE_NAME:-openldap}:${TAG:-latest}
    container_name: openldap
    restart: unless-stopped
    env_file:
      - ../.env.example
    environment:
      LDAP_ADMIN_PASSWORD: supersecret
      LDAP_ENABLE_TLS: "true"
      LDAP_ENABLE_LDAPS: "true"
      LDAP_REQUIRE_TLS: "true"
      LDAP_SIMPLE_BIND_MIN_SSF: "71"
      LDAP_ENABLE_MEMBEROF: "true"
      LDAP_ENABLE_REFINT: "true"
      LDAP_ENABLE_SYNCPROV: "true"
      LDAP_ENABLE_ACCESSLOG: "true"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - openldap_data:/var/lib/openldap/openldap-data
      - openldap_accesslog:/var/lib/openldap/accesslog
      - ./bootstrap:/docker-entrypoint-initdb.d:ro
      - ./custom-config/pre:/etc/openldap/custom-config/pre:ro
      - ./custom-config/post:/etc/openldap/custom-config/post:ro
      - ./custom-schema:/etc/openldap/custom-schema:ro
      - ./certs:/etc/openldap/certs:ro

volumes:
  openldap_data:
  openldap_accesslog:
